# Generated by Django 6.1 on 2026-09-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('blog', '0002_post_is_featured_post_status_post_summary_and_more'),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
