# settings.py — Central configuration: apps, database, middleware, templates, static files, security.
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""



import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY — used for cryptographic signing (sessions, CSRF tokens, password
# reset links). Must be kept private and never exposed in production.
SECRET_KEY = 'django-insecure-bti&4l0r=ixd!9s*&rcctlf%3gfvgysul916#&x*@qs0sz@@52'



# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG — when True, shows detailed error pages with full tracebacks.
# Must be False in production (security risk if left on).
DEBUG = True



# ALLOWED_HOSTS — list of domains/hostnames allowed to serve this site.
# Empty is fine locally; must list real domain(s) in production or Django rejects requests.
ALLOWED_HOSTS = []



# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'blog',
]



# MIDDLEWARE — a stack of independent processing layers that every request passes
# through (top to bottom) before reaching a view, and every response passes back
# through (bottom to top) before reaching the browser. Each layer handles its own
# concern (security, sessions, CSRF, auth, messages) independently of the others.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# ROOT_URLCONF — tells Django which urls.py file is the entry point for URL
# routing. Every incoming request's path is matched starting from this file,
# which typically delegates to each app's own urls.py.
ROOT_URLCONF = 'config.urls'



# TEMPLATES — configures Django's template engine. With APP_DIRS=True, Django
# automatically looks for a 'templates/' folder inside each installed app.
# DIRS (currently empty) can list additional project-wide template folders.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# WSGI_APPLICATION — tells WSGI-compatible production servers (e.g. Gunicorn)
# exactly where to find the callable that runs this Django project synchronously.
WSGI_APPLICATION = 'config.wsgi.application'



# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATABASES — configures the database connection. ENGINE selects the database
# driver (SQLite here; could be PostgreSQL/MySQL). NAME is the SQLite file path,
# or the database name for other engines (which also need USER/PASSWORD/HOST).
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES — configures the database connection. ENGINE selects the
# database driver (PostgreSQL here). NAME is the database name; USER,
# PASSWORD, HOST, and PORT come from environment variables (.env).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS — a list of rules Django checks a password against
# before allowing it to be set (e.g. on signup or password change): not too
# similar to user info, minimum length, not a common weak password, not all-numeric.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# LANGUAGE_CODE — the default language for text and formatting Django uses.
LANGUAGE_CODE = 'en-us'



# TIME_ZONE — the default timezone used for displaying dates/times to users.
TIME_ZONE = 'UTC'



# USE_I18N — enables Django's translation/internationalization system,
# allowing text to be translated based on LANGUAGE_CODE or the user's locale.
USE_I18N = True



# USE_TZ — stores all datetimes in the database as UTC and makes Python
# datetime objects timezone-aware, so times can be correctly converted
# for users in different timezones.
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# STATIC_URL — the URL prefix used in the browser to request static files
# (CSS, JS, images), e.g. /static/style.css. This is NOT the physical folder
# path on disk — just the address the browser uses to fetch these files.
STATIC_URL = 'static/'



# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# MAILERS — configures how Django sends emails. Console backend here just
# prints emails to the terminal instead of actually sending them (dev-only).
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}